src/blockchain/xaave/prices.spec.ts
src/blockchain/xaave/prices.ts
src/blockchain/xknc/prices.spec.ts
src/blockchain/xknc/prices.ts
src/blockchain/xsnx/prices.spec.ts

Fixed issue with prices api

---

package.json
src/blockchain/utils.spec.ts
src/blockchain/utils.ts
src/blockchain/xaave/burn.ts
src/blockchain/xaave/mint.ts
src/blockchain/xknc/burn.ts
src/blockchain/xknc/mint.ts
src/blockchain/xsnx/burn.ts
src/blockchain/xsnx/mint.ts
yarn.lock

Fixed issue with calculating min rate

---

src/blockchain/xaave/portfolio.ts
src/blockchain/xknc/portfolio.ts
src/blockchain/xsnx/portfolio.ts
src/xToken.spec.ts

Fixed issue with token equivalent calculation

---

.cspell.json
src/blockchain/exchanges/balancer.ts
src/blockchain/utils.ts
src/blockchain/xinch/portfolio.ts
src/blockchain/xinch/prices.spec.ts
src/blockchain/xinch/prices.ts
src/xToken.spec.ts
src/xToken.ts

Added get liquidity pool items method

---

src/blockchain/xaave/burn.ts
src/blockchain/xinch/burn.ts

Fixed issue with min expected rate on burn

---

src/blockchain/exchanges/balancer.ts
src/blockchain/exchanges/inch.ts
src/blockchain/utils.ts
src/xToken.ts

Added xINCH to liquidity pool item

---

src/blockchain/xinch/burn.spec.ts
src/blockchain/xinch/burn.ts

Fixed issue with estimated quantity on burn

---

src/blockchain/xsnx/prices.ts
src/types/xToken.d.ts

- Adds a `sellPriceUsd` return value to `getXSnxPrices`

Added sellPriceUsd to getXSnxPrices method

---

package.json
src/blockchain/utils.ts
src/blockchain/xaave/burn.ts
src/blockchain/xaave/mint.ts
src/blockchain/xaave/portfolio.ts
src/blockchain/xinch/portfolio.ts
src/blockchain/xknc/burn.ts
src/blockchain/xknc/mint.ts
src/blockchain/xknc/portfolio.ts
src/blockchain/xsnx/mint.ts
src/blockchain/xsnx/portfolio.ts
src/constants.ts
yarn.lock

Integrated 1Inch API to fetch expected rate

---

src/blockchain/exchanges/balancer.ts
src/blockchain/exchanges/helper.ts
src/blockchain/exchanges/inch.ts
src/blockchain/exchanges/uniswap.ts
src/blockchain/utils.ts
src/blockchain/xinch/helper.ts

Fixed liquidity pool price calculation

---

.cspell.json
src/blockchain/exchanges/uniswap.ts
src/blockchain/xaave/asset.ts
src/blockchain/xinch/asset.ts
src/blockchain/xknc/asset.ts
src/blockchain/xknc/helper.ts
src/blockchain/xknc/portfolio.ts
src/blockchain/xknc/prices.spec.ts
src/blockchain/xsnx/asset.ts
src/blockchain/xsnx/helper.ts
src/blockchain/xsnx/portfolio.ts
src/blockchain/xsnx/prices.spec.ts
src/blockchain/xsnx/redeem.ts
src/types/xToken.d.ts
src/xToken.ts

Added getXAssets method

---

src/blockchain/exchanges/balancer.ts
src/blockchain/exchanges/helper.ts
src/blockchain/exchanges/inch.ts
src/blockchain/exchanges/uniswap.ts
src/blockchain/xaave/portfolio.ts
src/blockchain/xaave/prices.ts
src/blockchain/xinch/portfolio.ts
src/blockchain/xinch/prices.ts
src/blockchain/xknc/portfolio.ts
src/blockchain/xknc/prices.ts
src/blockchain/xsnx/portfolio.ts
src/blockchain/xsnx/prices.ts
src/constants.ts
src/xToken.ts

Added additional error handling with default return values

---

src/blockchain/utils.ts
src/blockchain/xaave/burn.ts
src/blockchain/xaave/mint.ts
src/blockchain/xinch/burn.ts
src/blockchain/xinch/mint.ts
src/blockchain/xknc/burn.ts
src/blockchain/xknc/mint.ts
src/blockchain/xsnx/burn.ts
src/blockchain/xsnx/mint.ts
src/constants.ts
src/utils/index.ts

Added gas limit estimate for trading with ETH

---

src/blockchain/xaave/burn.ts
src/blockchain/xaave/mint.ts
src/blockchain/xinch/burn.ts
src/blockchain/xinch/mint.ts
src/blockchain/xknc/burn.ts
src/blockchain/xknc/mint.ts
src/blockchain/xsnx/burn.ts
src/blockchain/xsnx/mint.ts
src/constants.ts

Added default gas limit for approve/mint/burn transactions

---

src/blockchain/exchanges/inch.ts
src/blockchain/xaave/mint.ts
src/blockchain/xinch/burn.ts
src/blockchain/xinch/mint.ts
src/constants.ts
src/types/XAAVE.d.ts
src/types/factories/XAAVE__factory.ts
src/xToken.ts

Added affiliate param to xAAVE mint functionality

---

src/blockchain/xu3lp/prices.ts

Fixed USDC price to 1$

---

package.json
src/blockchain/xu3lp/redeem.ts
src/types/XU3LP.d.ts
src/types/factories/XU3LP__factory.ts
yarn.lock

Updated max redeem estimate logic for xU3LP assets

---

.husky/pre-commit
src/blockchain/utils.ts

- **What is the current behavior?** (You can also link to an open issue here)
- **What is the new behavior (if this is a feature change)?**
- **Other information**:

Fix xU3LPf token names

---

package.json
src/blockchain/exchanges/balancerV2.spec.ts
src/blockchain/exchanges/balancerV2.ts
src/constants.ts
src/xToken.ts
yarn.lock

Added Balancer V2 estimate for SNX trades

---

src/blockchain/exchanges/uniswapV3.spec.ts
src/constants.ts
src/xToken.spec.ts
src/xToken.ts

Added xAAVEa xAssetCLR pool for best return estimate

---

package.json
src/blockchain/clr/prices.ts
src/blockchain/lending/comptroller.spec.ts
src/blockchain/lending/liquidityPool.spec.ts
src/blockchain/lending/market.spec.ts
src/blockchain/lending/price.spec.ts
src/blockchain/xsnx/redeem.spec.ts
src/blockchain/xsnx/redeem.ts
src/types/GM.d.ts
src/types/factories/GM__factory.ts
yarn.lock

Fixed issue with calculating xSNXa maximum redeemable
